task = "export_candidates"
task_data_dir = "./testdata/tar_versions"
output_path = "./runs/finesse_candidates.jsonl"

[feature]
type = "finesse"
top_k_candidates = 16

[chunker]
type = "fast-cdc"
min_chunk_size = 4096
max_chunk_size = 16384
stop_mask = 8191
